"""
SCRIPT 14 — Figure 6: Layer-wise OOD AUROC
============================================
Generate Figure 6 from cross_domain.json (generated by script 08).

Input:
  results/table1/cross_domain.json

Output:
  results/figures/figure6_layerwise_auroc.png  (300 DPI)
  results/figures/figure6_layerwise_auroc.pdf

Run in Colab:
    %run /content/14_layerwise_auroc_figure.py
"""

import os, json
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

# ── Configuration ─────────────────────────────────────────────────────────────
DRIVE_ROOT   = '/content/drive/My Drive/pe_experiment'
DATA_PATH    = os.path.join(DRIVE_ROOT, 'results', 'table1', 'cross_domain.json')
OUT_FIG_DIR  = os.path.join(DRIVE_ROOT, 'results', 'figures')
os.makedirs(OUT_FIG_DIR, exist_ok=True)

PE_TYPES     = ['learned', 'sinusoidal', 'rope', 'alibi']
PE_LABELS    = {'learned': 'Learned', 'sinusoidal': 'Sinusoidal',
                'rope': 'RoPE', 'alibi': 'ALiBi'}
PE_COLORS    = {'learned': '#E24B4A', 'sinusoidal': '#185FA5',
                'rope': '#1D9E75', 'alibi': '#BA7517'}
PE_MARKERS   = {'learned': 'o', 'sinusoidal': 's', 'rope': '^', 'alibi': 'D'}

ALL_LAYERS   = list(range(0, 12))   # 0-indeksirani u JSON-u

# ── Load data ────────────────────────────────────────────────────────────
with open(DATA_PATH) as f:
    d = json.load(f)

print(f"Ucitano: {DATA_PATH}")

# ── Create figure ──────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 6))
fig.patch.set_facecolor('white')

smer_configs = [
    ('smer_a', 'Direction A: IN-100 → C-100  (Semantic Degradation)'),
    ('smer_b', 'Direction B: C-100 → IN-100  (Structural Pressure)'),
]

for ax, (smer_key, smer_title) in zip(axes, smer_configs):
    for pe in PE_TYPES:
        data = d.get(smer_key, {}).get(pe)
        if not data or 'layer_auroc' not in data:
            continue

        la    = data['layer_auroc']
        means = np.array([la.get(str(l), {}).get('mean', float('nan'))
                          for l in ALL_LAYERS])
        stds  = np.array([la.get(str(l), {}).get('std',  float('nan'))
                          for l in ALL_LAYERS])
        xs    = np.arange(1, 13)   # 1-indeksirani za prikaz

        ax.plot(xs, means,
                color=PE_COLORS[pe], marker=PE_MARKERS[pe],
                markersize=5, linewidth=1.8, label=PE_LABELS[pe], zorder=3)
        ax.fill_between(xs, means - stds, means + stds,
                        alpha=0.15, color=PE_COLORS[pe], zorder=2)

    # Referentne linije
    ax.axhline(y=0.5, color='#cccccc', linestyle='-',  linewidth=1.0, alpha=0.8)
    ax.axhline(y=0.6, color='#aaaaaa', linestyle='--', linewidth=1.0, alpha=0.6)
    ax.text(11.8, 0.51, 'random',    fontsize=7.5, color='#aaaaaa',
            ha='right', va='bottom')
    ax.text(11.8, 0.61, 'overconfident\nthreshold', fontsize=7.5,
            color='#aaaaaa', ha='right', va='bottom')

    # L3 sentinel
    ax.axvline(x=3, color='#888888', linestyle=':', linewidth=1.0, alpha=0.6)
    ax.text(3.1, 0.99, 'L3\n(best)', fontsize=7.5, color='#888888', va='top')

    ax.set_xlabel('Transformer Layer', fontsize=12)
    ax.set_ylabel('OOD AUROC', fontsize=12)
    ax.set_title(smer_title, fontsize=11, pad=10, color='#333333')
    ax.set_xticks(range(1, 13))
    ax.set_xlim(0.5, 12.5)
    ax.set_ylim(0.40, 1.02)
    ax.grid(True, alpha=0.25, linestyle='--', linewidth=0.7)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    if smer_key == 'smer_a':
        ax.legend(fontsize=10, framealpha=0.9, loc='lower left',
                  frameon=True, edgecolor='#dddddd')

fig.suptitle(
    'Figure 6: Layer-wise OOD AUROC — Attention Entropy as Uncertainty Score\n'
    'Cross-domain evaluation: in-distribution vs. OOD samples '
    '(shaded = ±σ, 3 seeds)',
    fontsize=12, y=1.01, color='#1a1a1a'
)
plt.tight_layout()

# ── Save ─────────────────────────────────────────────────────────────────────
png_path = os.path.join(OUT_FIG_DIR, 'figure6_layerwise_auroc.png')
pdf_path = os.path.join(OUT_FIG_DIR, 'figure6_layerwise_auroc.pdf')
fig.savefig(png_path, dpi=300, bbox_inches='tight', facecolor='white')
fig.savefig(pdf_path,           bbox_inches='tight', facecolor='white')
plt.close(fig)

print(f"✓ PNG: {png_path}")
print(f"✓ PDF: {pdf_path}")
